# Generated by Django 2.0.6 on 2020-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Приложите фотографию колеса:')),
                ('code', models.CharField(max_length=10, verbose_name='Код протектора')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('width', models.CharField(choices=[('275', '275'), ('295', '295'), ('315', '315')], max_length=5, verbose_name='Ширина')),
                ('height', models.CharField(choices=[('70', '70'), ('75', '75'), ('80', '80')], max_length=5, verbose_name='Высота')),
                ('radius', models.CharField(choices=[('22.5', '22.5')], max_length=5, verbose_name='Радиус')),
                ('speed_index', models.IntegerField(verbose_name='Индекс скорости')),
                ('tread_depth', models.IntegerField(verbose_name='Глубина протектора')),
                ('standard', models.FloatField(verbose_name='Какой-то стандарт')),
                ('oa_dia', models.IntegerField(verbose_name='OA DIA')),
                ('max_pressure', models.IntegerField(verbose_name='Максимальное давление(КРА/PSI)')),
                ('certificate', models.CharField(max_length=5, verbose_name='Сертификат качества')),
                ('distance', models.IntegerField(verbose_name='Преодолимая дистанция колёс')),
                ('max_loading', models.IntegerField(verbose_name='Максимальная нагрузка')),
            ],
        ),
    ]
