# Generated by Django 2.1.5 on 2020-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='type',
            field=models.CharField(max_length=2, null=True, verbose_name='Тип колеса'),
        ),
    ]
